import Link from "next/link";
import { PublicFooter, PublicHeader, SectionHeading, StorageIllustration } from "@/components/public-site";
import { UiIcon } from "@/components/ui-icon";

const services = [
  { key: "CLOUD", title: "Cloud y cifrado", icon: "storage", text: "Almacenamiento administrado en la nube para acceder, organizar y compartir los archivos del equipo.", points: ["Acceso desde diferentes dispositivos", "Organización por carpetas", "Gestión centralizada de archivos"] },
  { key: "ON-PREMISES", title: "Despliegue local", icon: "install", text: "Infraestructura alojada en el entorno de tu organización para tener control operativo de los datos.", points: ["Datos en infraestructura propia", "Políticas según tu entorno", "Control de almacenamiento local"] },
  { key: "HÍBRIDO", title: "Arquitectura híbrida", icon: "grid", text: "Combina cloud y almacenamiento local según las necesidades y políticas de la organización.", points: ["Estrategia flexible de destinos", "Alineación con tus operaciones", "Escala gradual"] },
] as const;

export default function ServicesPage() {
  return <main className="public-site"><PublicHeader />
    <section className="services-hero"><span className="public-kicker">ALMACENAMIENTO PARA TU ORGANIZACIÓN</span><h1>Infraestructura de almacenamiento potente, escalable y segura</h1><p>Gestiona, respalda y sincroniza los datos críticos de tu empresa en entornos cloud o locales, con un enfoque flexible.</p><div className="services-hero-visual"><StorageIllustration /><div className="services-visual-caption"><span>Mi espacio</span><span className="caption-badge">Sincronización disponible</span></div><div className="services-visual-list"><i>▤</i><span><b>Archivos de equipo</b><small>Organizados en un espacio común</small></span><span>•••</span></div><div className="services-visual-list"><i>▰</i><span><b>Infraestructura local</b><small>Conectada a tu estrategia de datos</small></span><span>•••</span></div></div><a className="services-scroll" href="#opciones">Explora las opciones <span>↓</span></a></section>
    <section className="public-section services-options" id="opciones"><SectionHeading eyebrow="LA NUEVA GENERACIÓN DEL ALMACENAMIENTO" title="Una solución para cada entorno" text="Conoce las opciones de almacenamiento que conforman la propuesta de Nexus."/><div className="service-cards">{services.map((service) => <article className="service-card" key={service.key}><div className="service-card-top"><span className="service-icon"><UiIcon name={service.icon} size={20} /></span><span className="service-tag">{service.key}</span></div><h2>{service.title}</h2><p>{service.text}</p><ul>{service.points.map((point) => <li key={point}><span>✓</span>{point}</li>)}</ul><Link href="/contacto">Consultar disponibilidad <span>→</span></Link></article>)}</div></section>
    <section className="services-security"><div className="services-security-inner"><div><span className="public-kicker">CONTROL Y PROTECCIÓN</span><h2>Tu infraestructura, con una visión clara</h2><p>Nexus está diseñado para mantener los archivos y sus metadatos en capas separadas, con controles organizacionales y permisos definidos por el sistema.</p><Link className="button public-button-outline" href="/#seguridad">Conocer el enfoque de seguridad</Link></div><div className="services-security-art"><div className="security-rings"><span>NX</span></div><div className="security-data-card"><i>✓</i><span><b>Organización protegida</b><small>Controles diseñados por tenant</small></span></div><div className="security-data-card"><i>◈</i><span><b>Datos estructurados</b><small>Metadatos separados del contenido</small></span></div></div></div><p className="security-footnote">Las capacidades dependen del despliegue e integración disponibles; consulta el estado actual con el equipo Nexus.</p></section>
    <section className="contact-cta"><div><span className="public-kicker">ENCUENTRA TU CONFIGURACIÓN</span><h2>¿Cloud, local o híbrido?</h2><p>Comparte tus necesidades y te ayudaremos a explorar la opción adecuada.</p></div><Link className="button public-button-coral" href="/contacto">Solicitar información <span>→</span></Link></section><PublicFooter /></main>;
}
