import Link from "next/link";
import { PublicFooter, PublicHeader } from "@/components/public-site";
import { PUBLIC_PLANS } from "@/lib/plans";

export default function PlansPage() {
  return <main className="public-site"><PublicHeader /><section className="plans-hero"><span className="public-kicker">PLANES NEXUS</span><h1>El espacio que tu organización necesita</h1><p>Compara capacidad, usuarios y vigencia para encontrar una opción adecuada para tu equipo.</p><a href="#catalogo" className="button public-button-coral">Ver planes <span>↓</span></a><div className="plans-hero-orbit" aria-hidden="true"><span>GB</span><i>⌁</i><i>+</i><i>◈</i></div></section>
    <section className="public-section public-plan-catalog" id="catalogo"><div className="plan-catalog-heading"><div><span className="public-kicker">CATÁLOGO PÚBLICO</span><h2>Opciones para empezar y crecer</h2><p>Los valores comerciales están sujetos al catálogo definitivo de Billing.</p></div><span className="catalog-mark">NEXUS <i>PLANES</i></span></div><div className="public-plans-grid">{PUBLIC_PLANS.map((plan) => <article className={`public-plan-card ${plan.id === "profesional" ? "public-plan-featured" : ""}`} key={plan.id}><div className="public-plan-top"><span className="public-plan-badge">{plan.id === "demo" ? "PARA COMENZAR" : "REFERENCIA DEL MOCKUP"}</span>{plan.id === "profesional" && <span className="popular-pill">POPULAR</span>}</div><h3>{plan.name}</h3><p className="public-plan-description">{plan.description}</p><div className="public-plan-price">{plan.priceUsd === 0 ? "Gratis" : `$${plan.priceUsd.toFixed(2)}`}<small>{plan.priceUsd === 0 ? "para demostración" : `USD · ${plan.priceSource}`}</small></div><div className="public-plan-specs"><div><span>Almacenamiento</span><b>{plan.storageGb} GB</b></div><div><span>Límite de usuarios</span><b>{plan.users === null ? "Por definir" : `${plan.users} usuarios`}</b></div><div><span>Vigencia</span><b>{plan.validity}</b></div></div><Link className={`button ${plan.id === "profesional" ? "public-button-purple" : "public-plan-secondary"}`} href={`/planes/${plan.id}`}>Ver detalles <span>→</span></Link></article>)}</div><div className="catalog-disclaimer"><span>i</span><p><b>Información de demostración.</b> El precio de US$59.99, 100 GB y 12 meses del plan Profesional se tomaron de los mockups. Allí no se especifica el límite de usuarios. No se procesan pagos reales.</p></div></section>
    <section className="plans-help"><div><span className="public-kicker">¿TIENES DUDAS?</span><h2>Te ayudamos a elegir</h2><p>Cuéntanos sobre tu organización y te orientamos sobre almacenamiento cloud, local o híbrido.</p></div><Link className="button public-button-coral" href="/contacto">Hablar con el equipo <span>→</span></Link></section><PublicFooter /></main>;
}
