-- migrate:up
-- Tablas del dominio iam (PK inline: una tabla sin PK nunca es un estado intermedio válido). FK, UNIQUE, CHECK e índices van en migraciones posteriores.

CREATE TABLE iam."user" (
  user_id                uuid             NOT NULL DEFAULT gen_random_uuid(),
  email                  varchar(255)     NOT NULL,
  password_hash          varchar(255)     NOT NULL,
  full_name              varchar(150)     NOT NULL,
  email_verified         boolean          NOT NULL DEFAULT false,
  mfa_enabled            boolean          NOT NULL DEFAULT false,
  mfa_secret_encrypted   varchar(255),
  is_super_admin         boolean          NOT NULL DEFAULT false,
  status                 iam.user_status  NOT NULL DEFAULT 'active',
  failed_login_attempts  smallint         NOT NULL DEFAULT 0,
  last_login_at          timestamptz,
  created_at             timestamptz      NOT NULL DEFAULT now(),
  updated_at             timestamptz,
  CONSTRAINT pk_user PRIMARY KEY (user_id)
);
COMMENT ON TABLE iam."user" IS 'Persona con cuenta en la plataforma. Puede pertenecer a varias organizaciones mediante iam.membership (AC-02).';
COMMENT ON COLUMN iam."user".user_id IS 'Identificador único del usuario';
COMMENT ON COLUMN iam."user".email IS 'Correo de acceso';
COMMENT ON COLUMN iam."user".password_hash IS 'Hash Argon2id';
COMMENT ON COLUMN iam."user".full_name IS 'Nombre completo';
COMMENT ON COLUMN iam."user".email_verified IS 'Verificado vía ONE_TIME_TOKEN';
COMMENT ON COLUMN iam."user".mfa_enabled IS 'TOTP activo';
COMMENT ON COLUMN iam."user".mfa_secret_encrypted IS 'Secreto TOTP cifrado';
COMMENT ON COLUMN iam."user".is_super_admin IS 'Indicador de plataforma';
COMMENT ON COLUMN iam."user".status IS 'active / inactive / locked';
COMMENT ON COLUMN iam."user".failed_login_attempts IS 'Bloqueo progresivo';
COMMENT ON COLUMN iam."user".last_login_at IS 'Última sesión iniciada';
COMMENT ON COLUMN iam."user".created_at IS 'Fecha de registro';
COMMENT ON COLUMN iam."user".updated_at IS 'Última modificación';

CREATE TABLE iam.role (
  role_id      smallint     GENERATED BY DEFAULT AS IDENTITY,
  name         varchar(50)  NOT NULL,
  description  text,
  CONSTRAINT pk_role PRIMARY KEY (role_id)
);
COMMENT ON TABLE iam.role IS 'Catálogo de roles de organización: tenant_admin y colaborador. Super Admin no es un rol: es user.is_super_admin.';
COMMENT ON COLUMN iam.role.role_id IS 'Identificador del rol';
COMMENT ON COLUMN iam.role.name IS 'tenant_admin / colaborador';
COMMENT ON COLUMN iam.role.description IS 'Alcance del rol';

CREATE TABLE iam.membership (
  membership_id    uuid                   NOT NULL DEFAULT gen_random_uuid(),
  user_id          uuid                   NOT NULL,
  organization_id  uuid                   NOT NULL,
  role_id          smallint               NOT NULL,
  status           iam.membership_status  NOT NULL DEFAULT 'active',
  created_at       timestamptz            NOT NULL DEFAULT now(),
  CONSTRAINT pk_membership PRIMARY KEY (membership_id)
);
COMMENT ON TABLE iam.membership IS 'Pertenencia de un usuario a una organización con un rol. El rol es por organización, no global del usuario.';
COMMENT ON COLUMN iam.membership.membership_id IS 'Identificador de la membresía';
COMMENT ON COLUMN iam.membership.user_id IS 'Usuario';
COMMENT ON COLUMN iam.membership.organization_id IS 'Organización de esta membresía';
COMMENT ON COLUMN iam.membership.role_id IS 'Rol del usuario en esa organización';
COMMENT ON COLUMN iam.membership.status IS 'active / suspended';
COMMENT ON COLUMN iam.membership.created_at IS 'Fecha de alta en la organización';

CREATE TABLE iam.one_time_token (
  token_id    uuid               NOT NULL DEFAULT gen_random_uuid(),
  user_id     uuid               NOT NULL,
  token_hash  varchar(255)       NOT NULL,
  purpose     iam.token_purpose  NOT NULL,
  expires_at  timestamptz        NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz        NOT NULL DEFAULT now(),
  CONSTRAINT pk_one_time_token PRIMARY KEY (token_id)
);
COMMENT ON TABLE iam.one_time_token IS 'Tokens de un solo uso (verificación de correo, restablecimiento de contraseña). Solo se guarda el hash.';
COMMENT ON COLUMN iam.one_time_token.token_id IS 'Identificador del token';
COMMENT ON COLUMN iam.one_time_token.user_id IS 'Usuario destinatario';
COMMENT ON COLUMN iam.one_time_token.token_hash IS 'Hash del token enviado por correo';
COMMENT ON COLUMN iam.one_time_token.purpose IS 'email_verification / password_reset';
COMMENT ON COLUMN iam.one_time_token.expires_at IS 'Vencimiento';
COMMENT ON COLUMN iam.one_time_token.used_at IS 'Momento de uso';
COMMENT ON COLUMN iam.one_time_token.created_at IS 'Fecha de emisión';

CREATE TABLE iam.session (
  session_id          uuid          NOT NULL DEFAULT gen_random_uuid(),
  user_id             uuid          NOT NULL,
  refresh_token_hash  varchar(255)  NOT NULL,
  ip_address          varchar(45),
  user_agent          varchar(255),
  created_at          timestamptz   NOT NULL DEFAULT now(),
  expires_at          timestamptz   NOT NULL,
  revoked_at          timestamptz,
  CONSTRAINT pk_session PRIMARY KEY (session_id)
);
COMMENT ON TABLE iam.session IS 'Sesiones de usuario (refresh token hasheado) para renovar el JWT y poder revocarlas.';
COMMENT ON COLUMN iam.session.session_id IS 'Identificador de sesión';
COMMENT ON COLUMN iam.session.user_id IS 'Usuario dueño';
COMMENT ON COLUMN iam.session.refresh_token_hash IS 'Hash del refresh token';
COMMENT ON COLUMN iam.session.ip_address IS 'IP de origen';
COMMENT ON COLUMN iam.session.user_agent IS 'Navegador / dispositivo';
COMMENT ON COLUMN iam.session.created_at IS 'Inicio de sesión';
COMMENT ON COLUMN iam.session.expires_at IS 'Expiración programada';
COMMENT ON COLUMN iam.session.revoked_at IS 'Cierre manual';

-- migrate:down
DROP TABLE iam.session;
DROP TABLE iam.one_time_token;
DROP TABLE iam.membership;
DROP TABLE iam.role;
DROP TABLE iam."user";
