-- migrate:up
-- Índices. Política: se indexan las columnas FK que se consultan o que PostgreSQL debe recorrer al borrar el padre,
-- salvo las que ya son prefijo de un UNIQUE/PK o apuntan a tablas diminutas (role) o son columnas "created_by" de auditoría.
-- Los índices parciales (WHERE) sirven a procesos concretos: reconciliador de cargas, purga de papelera, expiración de tokens/enlaces/reservas.
-- Los UNIQUE parciales (uq_*) son reglas de integridad: un destino por defecto, una KEK activa y una suscripción activa por organización;
-- sin permisos duplicados en la ACL.

CREATE INDEX ix_installation_request_organization_id ON admin.installation_request (organization_id);
CREATE INDEX ix_installation_request_pending ON admin.installation_request (created_at) WHERE status = 'Pendiente';
CREATE INDEX ix_installation_organization_id ON admin.installation (organization_id);
CREATE INDEX ix_installation_check_installation_checked_at ON admin.installation_check (installation_id, checked_at DESC);
CREATE INDEX ix_connection_secret_ref_installation_id ON admin.connection_secret_ref (installation_id);
CREATE INDEX ix_membership_organization_id ON iam.membership (organization_id);
CREATE INDEX ix_one_time_token_user_purpose ON iam.one_time_token (user_id, purpose);
CREATE INDEX ix_one_time_token_pending_expiry ON iam.one_time_token (expires_at) WHERE used_at IS NULL;
CREATE INDEX ix_session_user_id ON iam.session (user_id);
CREATE INDEX ix_session_active_expiry ON iam.session (expires_at) WHERE revoked_at IS NULL;
CREATE INDEX ix_team_member_user_id ON files.team_member (user_id);
CREATE INDEX ix_drive_owner_user_id ON files.drive (owner_user_id) WHERE owner_user_id IS NOT NULL;
CREATE INDEX ix_drive_team ON files.drive (organization_id, team_id) WHERE team_id IS NOT NULL;
CREATE INDEX ix_folder_drive_id ON files.folder (drive_id);
CREATE INDEX ix_folder_parent_folder_id ON files.folder (parent_folder_id) WHERE parent_folder_id IS NOT NULL;
CREATE INDEX ix_folder_destination ON files.folder (organization_id, destination_id) WHERE destination_id IS NOT NULL;
CREATE INDEX ix_folder_trash ON files.folder (deleted_at) WHERE is_deleted;
CREATE INDEX ix_file_organization_id ON files.file (organization_id);
CREATE INDEX ix_file_folder_id ON files.file (folder_id);
CREATE INDEX ix_file_trash ON files.file (deleted_at) WHERE is_deleted;
CREATE INDEX ix_file_version_kek_id ON files.file_version (kek_id);
CREATE INDEX ix_tenant_encryption_key_organization_id ON files.tenant_encryption_key (organization_id);
CREATE UNIQUE INDEX uq_tenant_encryption_key_one_active_per_organization ON files.tenant_encryption_key (organization_id) WHERE status = 'active';
CREATE UNIQUE INDEX uq_destination_one_default_per_organization ON files.destination (organization_id) WHERE is_default;
CREATE INDEX ix_upload_folder ON files.upload (organization_id, folder_id);
CREATE INDEX ix_upload_destination ON files.upload (organization_id, destination_id);
CREATE INDEX ix_upload_in_flight ON files.upload (status, updated_at) WHERE status IN ('Pendiente', 'Cargando', 'Confirmando', 'Limpieza pendiente');
CREATE INDEX ix_reservation_active_expiry ON files.reservation (expires_at) WHERE status = 'active';
CREATE INDEX ix_share_link_organization_id ON files.share_link (organization_id);
CREATE INDEX ix_share_link_version_id ON files.share_link (version_id);
CREATE INDEX ix_share_link_active_expiry ON files.share_link (expires_at) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX uq_resource_access_file_user ON files.resource_access (file_id, user_id) WHERE file_id IS NOT NULL AND user_id IS NOT NULL;
CREATE UNIQUE INDEX uq_resource_access_file_team ON files.resource_access (file_id, team_id) WHERE file_id IS NOT NULL AND team_id IS NOT NULL;
CREATE UNIQUE INDEX uq_resource_access_folder_user ON files.resource_access (folder_id, user_id) WHERE folder_id IS NOT NULL AND user_id IS NOT NULL;
CREATE UNIQUE INDEX uq_resource_access_folder_team ON files.resource_access (folder_id, team_id) WHERE folder_id IS NOT NULL AND team_id IS NOT NULL;
CREATE INDEX ix_resource_access_user_id ON files.resource_access (user_id) WHERE user_id IS NOT NULL;
CREATE INDEX ix_resource_access_team_id ON files.resource_access (team_id) WHERE team_id IS NOT NULL;
CREATE INDEX ix_subscription_organization_status ON billing.subscription (organization_id, status);
CREATE INDEX ix_subscription_plan_id ON billing.subscription (plan_id);
CREATE UNIQUE INDEX uq_subscription_one_active_per_organization ON billing.subscription (organization_id) WHERE status = 'active';
CREATE INDEX ix_plan_revision_subscription_status ON billing.plan_revision (subscription_id, status);
CREATE INDEX ix_billing_operation_subscription_simulated_at ON billing.billing_operation (subscription_id, simulated_at DESC);
CREATE INDEX ix_audit_event_organization_occurred_at ON audit.audit_event (organization_id, occurred_at DESC);
CREATE INDEX ix_audit_event_correlation_id ON audit.audit_event (correlation_id);
CREATE INDEX ix_audit_event_actor_occurred_at ON audit.audit_event (actor_id, occurred_at DESC) WHERE actor_id IS NOT NULL;
CREATE INDEX ix_audit_event_resource ON audit.audit_event (organization_id, resource_id, occurred_at DESC) WHERE resource_id IS NOT NULL;
CREATE INDEX ix_audit_chain_checkpoint_organization_created_at ON audit.audit_chain_checkpoint (organization_id, created_at DESC);

-- migrate:down
DROP INDEX audit.ix_audit_chain_checkpoint_organization_created_at;
DROP INDEX audit.ix_audit_event_resource;
DROP INDEX audit.ix_audit_event_actor_occurred_at;
DROP INDEX audit.ix_audit_event_correlation_id;
DROP INDEX audit.ix_audit_event_organization_occurred_at;
DROP INDEX billing.ix_billing_operation_subscription_simulated_at;
DROP INDEX billing.ix_plan_revision_subscription_status;
DROP INDEX billing.uq_subscription_one_active_per_organization;
DROP INDEX billing.ix_subscription_plan_id;
DROP INDEX billing.ix_subscription_organization_status;
DROP INDEX files.ix_resource_access_team_id;
DROP INDEX files.ix_resource_access_user_id;
DROP INDEX files.uq_resource_access_folder_team;
DROP INDEX files.uq_resource_access_folder_user;
DROP INDEX files.uq_resource_access_file_team;
DROP INDEX files.uq_resource_access_file_user;
DROP INDEX files.ix_share_link_active_expiry;
DROP INDEX files.ix_share_link_version_id;
DROP INDEX files.ix_share_link_organization_id;
DROP INDEX files.ix_reservation_active_expiry;
DROP INDEX files.ix_upload_in_flight;
DROP INDEX files.ix_upload_destination;
DROP INDEX files.ix_upload_folder;
DROP INDEX files.uq_destination_one_default_per_organization;
DROP INDEX files.uq_tenant_encryption_key_one_active_per_organization;
DROP INDEX files.ix_tenant_encryption_key_organization_id;
DROP INDEX files.ix_file_version_kek_id;
DROP INDEX files.ix_file_trash;
DROP INDEX files.ix_file_folder_id;
DROP INDEX files.ix_file_organization_id;
DROP INDEX files.ix_folder_trash;
DROP INDEX files.ix_folder_destination;
DROP INDEX files.ix_folder_parent_folder_id;
DROP INDEX files.ix_folder_drive_id;
DROP INDEX files.ix_drive_team;
DROP INDEX files.ix_drive_owner_user_id;
DROP INDEX files.ix_team_member_user_id;
DROP INDEX iam.ix_session_active_expiry;
DROP INDEX iam.ix_session_user_id;
DROP INDEX iam.ix_one_time_token_pending_expiry;
DROP INDEX iam.ix_one_time_token_user_purpose;
DROP INDEX iam.ix_membership_organization_id;
DROP INDEX admin.ix_connection_secret_ref_installation_id;
DROP INDEX admin.ix_installation_check_installation_checked_at;
DROP INDEX admin.ix_installation_organization_id;
DROP INDEX admin.ix_installation_request_pending;
DROP INDEX admin.ix_installation_request_organization_id;
